
services:
  database:
    image: ${DB_IMAGE}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication-service:
      build:
        context: .
        args:
          GITHUB_USERNAME: ${GITHUB_USERNAME}
          GITHUB_PASSWORD: ${GITHUB_PASSWORD}
      restart: no
      ports:
        - "${APP_PORT}:8080"
      environment:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_PASSWORD: ${GITHUB_PASSWORD}
        KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}

        DB_URL: ${DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DRIVER: ${DB_DRIVER}
        DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE}
        DB_MIN_IDLE_CONNECTIONS: ${DB_MIN_IDLE_CONNECTIONS}
        DB_IDLE_TIMEOUT_MS: ${DB_IDLE_TIMEOUT_MS}
        DB_MAX_LIFETIME_MS: ${DB_MAX_LIFETIME_MS}

        GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
        GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}

      depends_on:
        database:
          condition: service_healthy