services:
  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - app-network
      - auth-internal


  authentication-service:
#      build:
#        context: .
#        args:
#          REPO_USERNAME: ${REPO_USERNAME}
#          REPO_TOKEN: ${REPO_TOKEN}
      image: yohannesmata/authmat #:sha-b09a974
      restart: no
      ports:
        - "${APP_PORT}:8080"
      environment:
        SPRING_PROFILES_ACTIVE: prod
        KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}

        SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/${DB_NAME}
        SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
        SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
        SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
        SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 300000
        SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1800000

        GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
        GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      depends_on:
        auth-db:
          condition: service_healthy
      networks:
        - app-network
        - auth-internal

volumes:
  auth-db-data:

networks:
  app-network:
    external: true
  auth-internal:
    driver: bridge