application:
  name: AuthMat

spring:
  output:
    ansi:
      enabled: ALWAYS
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  profiles:
    active: dev
  application:
    name: authentication-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

management:
  endpoints:
    web:
#       Changes base endpoint from /actuator -> /manage-auth
#      base-path: /manage-auth

      exposure:
#         Specific endpoints can be selected, in this case, all endpoints are accessible.
#        include: "*"
        include: health, metrics, prometheus

  endpoint:
    health:
      show-details: always
#     enables just the /shutdown endpoint
#    shutdown:
#      enabled: true
    # Disabling the /info endpoint
#    info:
#      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

REDIS_HOST:
REDIS_PORT:

DB_URL:
DB_USERNAME:
DB_PASSWORD:
DB_DRIVER:
DB_MAX_POOL_SIZE:
DB_MIN_IDLE_CONNECTIONS:
DB_IDLE_TIMEOUT_MS:
DB_MAX_LIFETIME_MS:

ACCESS_TOKEN_VALIDITY_MINUTES:
ACCESS_TOKEN_KEY_SIZE:
ACCESS_TOKEN_JWT_ALGORITHM:
ACCESS_TOKEN_KEY_ALGORITHM:
ACCESS_TOKEN_HISTORY_TRACE:
ACCESS_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES:

REFRESH_TOKEN_VALIDITY_MINUTES:
REFRESH_TOKEN_HISTORY_TRACE:
REFRESH_TOKEN_KEY_SIZE:
REFRESH_TOKEN_KEY_ALGORITHM:
REFRESH_TOKEN_JWT_ALGORITHM:
REFRESH_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES:

AUTH_BASE_ENDPOINT:
USERS_BASE_ENDPOINT:
#sentry:
#  dsn: https://6f39834fb7758b3febdbe15a42abad93@o4509417075900416.ingest.us.sentry.io/4509417078194176
#  # Add data like request headers and IP for users,
#  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
#  send-default-pii: true