spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  output:
    ansi:
      enabled: ALWAYS
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  application:
    name: authmat
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

management:
  endpoints:
    web:
      base-path: /authmat-actuator
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

authmat:
  system:
    credentials:
      #enabled: ${ENABLE_SYSTEM_USER}
      username: ${AUTHMAT_USERNAME:}
      password: ${AUTHMAT_PASSWORD:}
    token:
      access-token-validity-minutes: ${ACCESS_TOKEN_VALIDITY_MINUTES:15}
      access-token-key-size: ${ACCESS_TOKEN_KEY_SIZE:2048}
      access-token-jwt-algorithm: ${ACCESS_TOKEN_JWT_ALGORITHM:RS256}
      access-token-key-algorithm: ${ACCESS_TOKEN_KEY_ALGORITHM:RSA}
      access-token-history-trace: ${ACCESS_TOKEN_HISTORY_TRACE:10}
      access-token-signing-key-rotation-rate-minutes: ${ACCESS_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES:86400}

      refresh-token-validity-minutes: ${REFRESH_TOKEN_VALIDITY_MINUTES:180}
      refresh-token-key-size: ${REFRESH_TOKEN_KEY_SIZE:2048}
      refresh-token-key-algorithm: ${REFRESH_TOKEN_KEY_ALGORITHM:RS256}
      refresh-token-jwt-algorithm: ${REFRESH_TOKEN_JWT_ALGORITHM:RSA}
      refresh-token-history-trace: ${REFRESH_TOKEN_HISTORY_TRACE:10}
      refresh-token-signing-key-rotation-rate-minutes: ${REFRESH_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES:86400}
    endpoints:
      auth-base-endpoint: ${AUTH_BASE_ENDPOINT}
      users-base-endpoint: ${USERS_BASE_ENDPOINT}