logging:
  pattern:
    console: "%d %-5level %logger{36} - %msg%n"
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      format_sql: true
    database: postgresql

  output:
    ansi:
      enabled: ALWAYS

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

application:
  name: Authentication

management:
  endpoints:
    web:
      # Changing the base endpoint from /actuator -> /manage-auth
      base-path: /manage-auth
      exposure:
        # Specific endpoints can be selected, in this case, all endpoints are accessible.
        include: *

  endpoint:
    # enables just the /shutdown endpoint
    shutdown:
      enabled: true
    # Disabling the /info endpoint
    info:
      enabled: false

# All required
cache:
  host: ${CACHE_HOST}
  port: ${CACHE_PORT}

# The first four variables ARE required, the rest, optional.
db:
  jdbc-url: ${DB_JDBC_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver: ${DB_DRIVER}
  # Each variable below has a default value.
  max-pool-size: ${DB_MAX_POOL_SIZE}
  min-idle-connections: ${DB_MIN_IDLE_CONNECTIONS}
  idle-timeout-ms: ${DB_IDLE_TIMEOUT_MS}
  max-lifetime-ms: ${DB_MAX_LIFETIME_MS}

# Not required, each endpoint has a default.
endpoints:
  auth:
    base: ${AUTH_BASE_ENDPOINT}
    login: ${AUTH_LOGIN_ENDPOINT}
    register: ${AUTH_REGISTER_ENDPOINT}
    refresh: ${AUTH_REFRESH_ENDPOINT}
    logout: ${AUTH_LOGOUT_ENDPOINT}
  credentials:
    base: ${CREDENTIALS_BASE_ENDPOINT}
    username: ${CREDENTIALS_USERNAME_ENDPOINT}
    email: ${CREDENTIALS_EMAIL_ENDPOINT}
    password: ${CREDENTIALS_PASSWORD_ENDPOINT}
  roles: