on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven


      - name: Configure Maven for GitHub packages
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.REPO_USERNAME }}</username>
                <password>${{ secrets.REPO_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF
        shell: bash

      - name: Build and test
        run: mvn clean verify -B
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/authmat
          tags: |
            type=ref, type=branch
            type=ref, event=tag
            type=sha
            

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/authmat:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
            REPO_TOKEN: ${{ secrets.REPO_TOKEN }}


      - name: Run docker-compose for integration tests
        run: |
          docker-compose up -d auth-db
          sleep 15  # give Postgres time to initialize
          mvn verify -Pintegration-tests
          docker-compose down -v